/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/dish.glb 
Author: 18se02it016 (https://sketchfab.com/18se02it016)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/falafel-food-dish-dc300ae647f645d897546962525a78e5
Title: Falafel food dish
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Pizza from "./Pizza";

const Falafel = (props) => {
  const { nodes, materials } = useGLTF("public/models/dish.glb");
  return (
    <>
      <group visible={props.visible} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group scale={1.975} position={[-0.001, -0.006, 0.501]}>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["tabakKare_object.015_material"]}
              position={[-0.001, -0.006, -0.001]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials["24_object.017_material"]}
              position={[-0.001, -0.006, -0.001]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials["KaseKucuk_Cylinder.007_material"]}
              position={[-0.001, -0.006, -0.001]}
              rotation={[Math.PI / 2, 0, 0]}
            />
          </group>
        </group>
      </group>
    </>
  );
};

useGLTF.preload("/dish.glb");

export default Falafel;
