/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/pizza.glb 
Author: erebus3d (https://sketchfab.com/erebus3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-cdc2c970c84244b3b3293dd022b4fdfa
Title: Pizza
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Pizza = (props) => {
  const { nodes, materials } = useGLTF("public/models/pizza.glb");
  return (
    <group
      visible={props.visible}
      {...props}
      dispose={null}
      position={[0, 0.51, 0]}
    >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Object_2_Material__2001_0.geometry}
            material={materials["Material__2.001"]}
            position={[-10.891, 426.502, 5.021]}
            rotation={[Math.PI, 0, 0]}
            scale={26.463}
          />
          <mesh
            geometry={nodes.piza_low_01Group259_lambert1_0.geometry}
            material={materials.lambert1}
            position={[-123.275, 533.782, -16.404]}
            scale={235.277}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/pizza.glb");

export default Pizza;
