/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/wine_bottle_and_glass.glb 
Author: JoeDev (https://sketchfab.com/JoeDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wine-bottle-and-glass-13027525814d4c4ea07d4e12549cb9ef
Title: Wine Bottle and Glass
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Spoons = (props) => {
  const { nodes, materials } = useGLTF("/models/spoons.glb");
  return (
    <group {...props} dispose={null} scale={0.1} position={[0.1, 0.55, 0.6]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Silverware_MatMain}
        position={[0, 0, 0.942]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Silverware_MatMain}
        position={[0, 0, -0.031]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Silverware_MatMain}
        position={[0, 0, -0.911]}
      />
    </group>
  );
};

useGLTF.preload("/models/whiskey.glb");

export default Spoons;
