/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/table.glb 
Author: shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-acd1cef307b94803846d624b251a4e63
Title: Wooden Table
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Table = (props) => {
  const { nodes, materials } = useGLTF("/models/table.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.036}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Default}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/table.glb");

export default Table;
