/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/wine_bottle_and_glass.glb 
Author: JoeDev (https://sketchfab.com/JoeDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wine-bottle-and-glass-13027525814d4c4ea07d4e12549cb9ef
Title: Wine Bottle and Glass
*/

import React, { useContext, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import Context from "../context";

const WineBottle = (props) => {
  const { nodes, materials } = useGLTF("/models/whiskey.glb");
  const { tableItems, setTableItems } = useContext(Context);

  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, 0.51, -0.5]}
        scale={0.032}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          {/* cigaret */}
          {tableItems.cigarette && (
            <>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials.Ceramic}
                position={[0.994, 0.232, -2.89]}
                rotation={[0, -1.21, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials.Pepel}
                position={[0.994, 0.39, -2.89]}
                rotation={[0, -1.21, 0]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18.geometry}
                material={materials.Caigaret}
                position={[2.858, 0.76, -3.599]}
                rotation={[-1.011, -0.953, -0.915]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials.Caigaret}
                position={[0.315, 0.375, -2.717]}
                rotation={[0.325, -0.021, -0.121]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials.Caigaret}
                position={[0.981, 0.432, -2.968]}
                rotation={[-3.013, -0.722, 0.048]}
              />
            </>
          )}

          {/* cigaret */}
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/whiskey.glb");

export default WineBottle;
